name: Test

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [ "3.10", "3.13" ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: python -m unittest discover -t src -s test

  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: psf/black@24.10.0
